name: Cloud check in action
on:
  push:
    branches:
      - main
      - dev
  watch:
    types: started
  workflow_dispatch:
  schedule:
    - cron: 35 3 * * *
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: user
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 18
      - name: init secrets
        uses: shine1594/secrets-to-env-action@master
        with:
          secrets: ${{ toJSON(secrets) }}
          secrets_env: production
          prefix_prod: ""
          file_name_prod: .env
      - name: init
        run: npm install
      - name: run
        id: run
        uses: nick-fields/retry@master
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm start
     
      - name: Delete old workflow run
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 50
